# Generated by Django 5.2.4 on 2025-12-18 03:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Palmteccustomerdetails',
        #     fields=[
        #         ('upideviceserialnumber', models.CharField(db_column='upiDeviceSerialNumber', max_length=24, primary_key=True, serialize=False)),
        #         ('uniqueidentifier', models.CharField(blank=True, db_column='uniqueIdentifier', max_length=24, null=True)),
        #         ('customercode', models.BigIntegerField(db_column='customerCode')),
        #         ('customername', models.CharField(blank=True, db_column='customerName', max_length=128, null=True)),
        #         ('isapproved', models.IntegerField(blank=True, db_column='isApproved', null=True)),
        #         ('isdeleted', models.IntegerField(blank=True, db_column='isDeleted', null=True)),
        #         ('createdon', models.DateTimeField(blank=True, db_column='createdOn', null=True)),
        #         ('modifiedon', models.DateTimeField(blank=True, db_column='modifiedOn', null=True)),
        #         ('clicenseurl', models.CharField(blank=True, db_column='cLicenseURL', max_length=255, null=True)),
        #         ('versiondetails', models.CharField(blank=True, db_column='versionDetails', max_length=12, null=True)),
        #         ('devicetype', models.CharField(blank=True, max_length=24, null=True)),
        #         ('company', models.CharField(blank=True, max_length=24, null=True)),
        #     ],
        #     options={
        #         'db_table': 'palmteccustomerdetails',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Serialdata',
        #     fields=[
        #         ('serialnumber', models.CharField(db_column='serialNumber', max_length=18, primary_key=True, serialize=False)),
        #         ('isapproved', models.IntegerField(blank=True, db_column='isApproved', null=True)),
        #         ('isallocated', models.IntegerField(blank=True, db_column='isAllocated', null=True)),
        #         ('createdate', models.DateTimeField(blank=True, db_column='createDate', null=True)),
        #         ('modifieddate', models.DateTimeField(blank=True, db_column='modifiedDate', null=True)),
        #         ('category', models.CharField(blank=True, max_length=24, null=True)),
        #         ('deviceid', models.CharField(blank=True, db_column='deviceId', max_length=12, null=True)),
        #         ('imei', models.BigIntegerField(blank=True, db_column='IMEI', null=True)),
        #         ('imsi', models.BigIntegerField(blank=True, db_column='IMSI', null=True)),
        #     ],
        #     options={
        #         'db_table': 'serialdata',
        #         'managed': False,
        #     },
        # ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
