# Generated by Django 5.2.4 on 2025-12-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Palmteccustomerdetails',
        #     fields=[
        #         ('upideviceserialnumber', models.CharField(db_column='upiDeviceSerialNumber', max_length=24, primary_key=True, serialize=False)),
        #         ('uniqueidentifier', models.CharField(blank=True, db_column='uniqueIdentifier', max_length=24, null=True)),
        #         ('customercode', models.BigIntegerField(db_column='customerCode')),
        #         ('customername', models.CharField(blank=True, db_column='customerName', max_length=128, null=True)),
        #         ('isapproved', models.IntegerField(blank=True, db_column='isApproved', null=True)),
        #         ('isdeleted', models.IntegerField(blank=True, db_column='isDeleted', null=True)),
        #         ('createdon', models.DateTimeField(blank=True, db_column='createdOn', null=True)),
        #         ('modifiedon', models.DateTimeField(blank=True, db_column='modifiedOn', null=True)),
        #         ('clicenseurl', models.CharField(blank=True, db_column='cLicenseURL', max_length=255, null=True)),
        #         ('versiondetails', models.CharField(blank=True, db_column='versionDetails', max_length=12, null=True)),
        #         ('devicetype', models.CharField(blank=True, max_length=24, null=True)),
        #         ('company', models.CharField(blank=True, max_length=24, null=True)),
        #     ],
        #     options={
        #         'db_table': 'palmteccustomerdetails',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Serialdata',
        #     fields=[
        #         ('serialnumber', models.CharField(db_column='serialNumber', max_length=18, primary_key=True, serialize=False)),
        #         ('isapproved', models.IntegerField(blank=True, db_column='isApproved', null=True)),
        #         ('isallocated', models.IntegerField(blank=True, db_column='isAllocated', null=True)),
        #         ('createdate', models.DateTimeField(blank=True, db_column='createDate', null=True)),
        #         ('modifieddate', models.DateTimeField(blank=True, db_column='modifiedDate', null=True)),
        #         ('category', models.CharField(blank=True, max_length=24, null=True)),
        #         ('deviceid', models.CharField(blank=True, db_column='deviceId', max_length=12, null=True)),
        #         ('imei', models.BigIntegerField(blank=True, db_column='IMEI', null=True)),
        #         ('imsi', models.BigIntegerField(blank=True, db_column='IMSI', null=True)),
        #     ],
        #     options={
        #         'db_table': 'serialdata',
        #         'managed': False,
        #     },
        # ),
    ]
